name: Gulp src test
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install and run
        run: |
          npm install
          npm run srcRelativeTest
        
