name: Gulp src test
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: run
      # run: cd build && ../node_modules/.bin/gulp srcRelativeTest
      run: ls && echo '\n' && cd .. && ls && echo '\n' && cd .. && ls && echo '\n' && cd .. && pwd && echo '\n' && ls && echo '\n'
